name: Scheduled Data Update

on:
  schedule:
    - cron: "45 10 * * *"

defaults:
  run:
    shell: bash

jobs:
  runDataUpdate:
    name: Run Data Update
    runs-on: ubuntu-latest
    env:
      REPO_DIR: main
      TIMESTAMP: X
    steps:
      - name: Store timestamp
        run: |
          echo "TIMESTAMP=$(date -u +"%F-%H")" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_DIR }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "${{ env.REPO_DIR }}/_visualize/scripts/requirements.txt"
      - name: Install dependencies
        run: pip install -r $REPO_DIR/_visualize/scripts/requirements.txt
      - name: Run update script
        run: ./$REPO_DIR/.github/scripts/update.sh
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub App Installation Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Git config
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - name: Commit updated data
        run: |
          git stash
          git pull --ff-only
          git stash pop
          git add -A .
          git commit -m "${{ env.TIMESTAMP }} Data Update by ${{ steps.app-token.outputs.app-slug }}"
          git push
      - name: Show health stats
        if: ${{ always() }}
        run: |
          cat $REPO_DIR/_visualize/LAST_MASTER_UPDATE.txt || true
          echo "Warning Count: $(grep -c 'Warning' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
          echo "From Timeouts: $(grep -c 'but failed' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
          echo "Limit Reached: $(grep -c 'rate limit exceeded' $REPO_DIR/_visualize/LAST_MASTER_UPDATE.log)"
      - name: Save log files
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: logfiles_${{ env.TIMESTAMP }}_update
          path: |
            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.txt
            ${{ env.REPO_DIR }}/_visualize/LAST_MASTER_UPDATE.log
